# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: RunPipelines@1
  inputs:
    serviceConnection: 'Run Pipeline Service Connection'
    project: 'syncier test'
    folderPath: '\'
    buildDefinition: 'TsuyoshiUshio.TerrformApply.CI'
    setBranch: true
    Branch: '$(Build.SourceBranch)'
    targetType: 'inline'
    buildParameters: '[{"hello":"world"}]'
    customPrefix: 'Run'
    waitForQueuedBuildsToFinish: true
    waitRefreshTime: '10'
    waitTimeOut: '120'
    storeInOutputVariable: false


- task: CmdLine@2
  displayName: Switch to $(CURRENT_BRANCH)
  inputs:
    script: |
      echo "BUILD_SOURCEBRANCH: ${BUILD_SOURCEBRANCH}"
      echo "System.PullRequest.SourceBranch: $(System.PullRequest.SourceBranch)"
      git switch $BUILD_SOURCEBRANCH
      git pull