# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: 11645770-d18e-11e8-8f5b-1b8b62612b3b@0
  displayName: terraform install
  inputs:
    terraformVersion: '0.12.20'
- task: 721c3f90-d938-11e8-9d92-09d7594721b5@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'rguthrie-tsushi(7577383f-1b95-479e-b32d-3c38c6166cc9)'
    backendAzureRmResourceGroupName: 'remove-spike-rg'
    backendAzureRmStorageAccountName: 'tsushispike'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'example.tfstate'

- task: 721c3f90-d938-11e8-9d92-09d7594721b5@0
  displayName: Terraform Apply to $(Build.SourceBranch)
  inputs:
    command: 'apply'
    environmentServiceName: 'rguthrie-tsushi(7577383f-1b95-479e-b32d-3c38c6166cc9)'
